### PR TITLE
Add Web Demo & Docker environment 

### PR DESCRIPTION
**Pull request by chenxwh**
Hi @vis-opt-group! 👋 

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can try out your model! View it here: https://replicate.com/vis-opt-group/sci. You can find the docker file under the tab ‘run on your own computer’. 

We have added some examples to the page, but do claim the page so you can own the page, customise the [Example](https://replicate.com/vis-opt-group/sci/examples) gallery as you like, push any future update to the web demo, and we'll feature it on our website and tweet about it too. You can find the 'Claim this model' button on the top of the page. When the page is claimed, it will be automatically linked to the arXiv website as well (under “Demos”).

In case you're wondering who I am, I'm from [Replicate](https://replicate.com/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Comment by vis-opt-group** [comment]
Hello @chenxwh

Thank you very much for your valuable suggestions, we have uploaded the code on the corresponding website. You are welcome to use our models for debugging. Finally, thanks again for your suggestion.

**Comment by vis-opt-group** [comment]
Hello @chenxwh

Thank you very much for your valuable suggestions, we have uploaded the code on the corresponding website. You are welcome to use our models for satisfying your demand. Finally, thanks again for your suggestion.

**Comment by dfhsjakdf** [comment]
Hello,  @vis-opt-group!
I would like to ask a question about weight storage. In your program, weights generated at the end of each epoch are saved. How does your team select and save the best weights (.pth files)?

**Comment by SDASADASDDASD** [comment]
你好，为什么在train.py只提供低光照训练和测试数据集路径，不需要正常的训练和测试数据集路径进行配对吗？

**Pull request closed without merging**
